version: '3.7'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8051
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8051:8051
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: just_postgresql
    image: postgres:12.0-alpine
    env_file:
      - ./.env.db.dev
    expose:
      - 5438
    ports:
      - 5438:5438
    command: -p 5438
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: